apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: streaming
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.212
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      name: http
