apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: https://unsplash.com/photos/a-faint-nebula-glows-against-a-starry-night-sky-9wGI-g3rA-E
  custom.css: ""
  custom.js: ""
  services.yaml: |
    - Monitoring:
        - Grafana:
            icon: grafana.svg
            href: http://grafana.homelab/login
        - Headlamp:
            icon: headlamp.svg
            href: http://headlamp.homelab

    - Network:
        - Pi-hole:
            icon: pi-hole.svg
            href: http://pihole.homelab/admin
        - Router:
            icon: mdi-router-network
            href: http://192.168.0.1
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
        - ProtonVPN:
            icon: proton-vpn.svg
            href: https://account.proton.me/u/2/vpn/dashboardV2

    - Streaming:
        - Jellyfin:
            icon: jellyfin.svg
            href: http://jellyfin.homelab:8096
        - Jellyseerr:
            icon: jellyseerr.svg
            href: http://jellyseerr.homelab
        - qUI:
            icon: qui.svg
            href: http://qui.homelab:7476
        - Radarr:
            icon: radarr.svg
            href: http://radarr.homelab:7878
        - Sonarr:
            icon: sonarr.svg
            href: http://sonarr.homelab:8989
        - Prowlarr:
            icon: prowlarr.svg
            href: http://prowlarr.homelab:9696
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.svg
              href: https://github.com/lamiphil
              description: ""
        - ChatGPT:
            - icon: chatgpt.svg
              href: https://chatgpt.com
              description: ""

    - Entertainment:
        - Youtube:
            - icon: youtube.svg
              href: https://youtube.com
              description: ""
        - Soundcloud:
            - icon: mdi-soundcloud
              href: https://soundcloud.com
              description: ""
    - Communication:
        - Messenger:
            - icon: facebook-messenger.svg
              href: https://messenger.com
              description: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
