apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.svg
              href: https://github.com/lamiphil
              description: ""
        - ChatGPT:
            - icon: chatgpt.svg
              href: https://chatgpt.com
              description: ""

    - Entertainment:
        - Youtube:
            - icon: youtube.svg
              href: https://youtube.com
              description: ""
        - Soundcloud:
            - icon: mdi-soundcloud
              href: https://soundcloud.com
              description: ""
    - Communication:
        - Messenger:
            - icon: facebook-messenger.svg
              href: https://messenger.com
              description: ""
  services.yaml: |
    - Monitoring:
        - Grafana:
            icon: grafana.svg
            href: http://grafana.homelab/login

    - Network:
        - Pi-hole:
            icon: pi-hole.svg
            href: http://pihole.homelab/admin
        - Router:
            icon: mdi-router-network
            href: http://192.168.0.1
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines

    - Streaming:
        - Jellyfin:
            icon: jellyfin.svg
            href: http://jellyfin.homelab:8096
        - Transmission:
            icon: transmission.svg
            href: http://transmission.homelab:9091
        - Radarr:
            icon: radarr.svg
            href: http://radarr.homelab:7878
        - Sonarr:
            icon: sonarr.svg
            href: http://sonarr.homelab:8989
        - Prowlarr:
            icon: prowlarr.svg
            href: http://prowlarr.homelab:9696
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
