apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.svg
              href: https://github.com/lamiphil
              description: ""
    - Entertainment:
        - Youtube:
            - icon: youtube.svg
              href: https://youtube.com
              description: ""
        - Soundcloud:
            - icon: mdi-soundcloud
              href: https://soundcloud.com
              description: ""
    - Communication:
        - Messenger:
            - icon: facebook-messenger.svg
              href: https://messenger.com
              description: ""
  services.yaml: |
    - Monitoring:
        - Grafana:
            icon: grafana.svg
            href: http://grafana.homelab/login

    - Network:
        - Pi-hole:
            icon: pi-hole.svg
            href: http://pihole.homelab/admin

    - Entertainment:
        - Jellyfin:
            icon: jellyfin.svg
            href: http://jellyfin.homelab:8096
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
