apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: streaming
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.213
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      name: http
