apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: streaming
spec:
  type: LoadBalancer
  selector:
    app: qui
  ports:
    - name: http
      port: 7476
      targetPort: 7476
      protocol: TCP
