apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      nodeSelector:
        role: jellyfin-storage
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
          ports:
            - containerPort: 9091   # Web UI
              name: http
            # Ports torrent, on peut les ouvrir plus tard au besoin :
            # - containerPort: 51413
            #   name: torrent-tcp
            #   protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          hostPath:
            path: /srv/streaming/transmission/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /srv/media/downloads
            type: DirectoryOrCreate
        - name: watch
          hostPath:
            path: /srv/streaming/transmission/watch
            type: DirectoryOrCreate
