apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-vpn
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-vpn
  template:
    metadata:
      labels:
        app: transmission-vpn
    spec:
      nodeSelector:
        role: streaming
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
          ports:
            - containerPort: 9091
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "700m"
              memory: "600Mi"

        - name: vpn
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            # PIA + OpenVPN
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-openvpn-credentials
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-openvpn-credentials
                  key: OPENVPN_PASSWORD
            - name: SERVER_REGIONS
              value: "CA Montreal"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: TZ
              value: "America/Toronto"
          ports:
            - name: http
              containerPort: 9091
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun

      volumes:
        - name: config
          hostPath:
            path: /srv/streaming/transmission/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /srv/media/downloads
            type: DirectoryOrCreate
        - name: watch
          hostPath:
            path: /srv/streaming/transmission/watch
            type: DirectoryOrCreate
        - name: gluetun-config
          emptyDir: {}
