apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: streaming
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.206
  selector:
    app: transmission-vpn
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      name: http
