apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      nodeSelector:
        role: streaming
      containers:
        # qBittorrent
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.1.4-r1-ls431
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: webui
              containerPort: 8080
            - name: bittorrent
              containerPort: 6881
          volumeMounts:
            - name: qb-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "700m"
              memory: "600Mi"

        # VPN (Gluetun)
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "wireguard"
            # Permets à qbit d’être accessible (UI + ports torrent) à travers le firewall gluetun
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "8080,6881"
            - name: FIREWALL_INPUT_PORTS
              value: "8080,6881"
            - name: DOT
              value: "off"
            # évite les restarts causés par ICMP
            - name: HEALTHCHECK_TARGETS
              value: "cloudflare.com:443"
            - name: HEALTHCHECK_METHOD
              value: "tcp"
            # autorise ton LAN + les CIDR k3s
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/16,10.43.0.0/16,192.168.0.0/24"
            - name: VERSION_CHECK
              value: "off"

          envFrom:
            - secretRef:
                name: qbittorrent-vpn-wg
          volumeMounts:
            - name: wireguard-config
              mountPath: /gluetun/wireguard/wg0.conf
              subPath: wg0.conf
              readOnly: true
            - name: dev-net-tun
              mountPath: /dev/net/tun

      volumes:
        - name: qb-config
          hostPath:
            path: /srv/streaming/qbittorrent/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /srv/media/downloads
            type: DirectoryOrCreate
        - name: watch
          hostPath:
            path: /srv/streaming/qbittorrent/watch
            type: DirectoryOrCreate

        - name: wireguard-config
          secret:
            secretName: qbittorrent-vpn-wg
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
