apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: streaming
spec:
  type: ClusterIP
  selector:
    app: qbittorrent-vpn
  ports:
    - name: webui
      protocol: TCP
      port: 8080
      targetPort: 8080

