apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: streaming
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.210
  selector:
    app: qbittorrent-vpn
  ports:
    - name: webui
      protocol: TCP
      port: 8080
      targetPort: 8080

